/*----------------------------------------------------------------------
 * test_ddl_deparse.c
 *		Support functions for the test_ddl_deparse module
 *
 * Copyright (c) 2014-2026, PostgreSQL Global Development Group
 *
 * IDENTIFICATION
 *	  src/test/modules/test_ddl_deparse/test_ddl_deparse.c
 *----------------------------------------------------------------------
 */
#include "postgres.h"

#include "access/xact.h"
#include "catalog/namespace.h"
#include "commands/ddl_deparse.h"
#include "commands/event_trigger.h"
#include "funcapi.h"
#include "nodes/execnodes.h"
#include "tcop/deparse_utility.h"
#include "tcop/tcopprot.h"
#include "tcop/utility.h"
#include "utils/builtins.h"
#include "utils/guc.h"
#include "utils/memutils.h"
#include "utils/resowner.h"
#include "utils/tuplestore.h"

PG_MODULE_MAGIC;

PG_FUNCTION_INFO_V1(get_command_type);
PG_FUNCTION_INFO_V1(get_command_tag);
PG_FUNCTION_INFO_V1(get_altertable_subcmdinfo);
PG_FUNCTION_INFO_V1(capture_deparsed_ddl);

typedef struct TestDDLDeparseErrorInfo
{
	const char *orig_ddl;
	const char *deparsed_ddl;
} TestDDLDeparseErrorInfo;

typedef enum
{
	PRINT_DEPARSED_OFF,
	PRINT_DEPARSED_JSON,
	PRINT_DEPARSED_TEXT,
	PRINT_DEPARSED_BOTH,
} PrintDeparsedDDL;

static const struct config_enum_entry print_deparsed_ddl_options[] = {
	{"off", PRINT_DEPARSED_OFF, false},
	{"json", PRINT_DEPARSED_JSON, false},
	{"text", PRINT_DEPARSED_TEXT, false},
	{"both", PRINT_DEPARSED_BOTH, false},
	{NULL, 0, false}
};

/* GUCs */
static bool execute_deparsed_ddl = false;
static int	print_deparsed_ddl = PRINT_DEPARSED_OFF;
static bool log_declined_commands = false;

static ProcessUtility_hook_type next_ProcessUtility_hook = NULL;

/*
 * The statement currently being captured, as the user wrote it, or NULL when
 * no capture is in progress.  The deparser works from the raw statement, but
 * execution rewrites it in place (transformCreateStmt updates relpersistence,
 * expands serial, and so on), so the module runs every captured statement
 * with readOnlyTree forced on: what ProcessUtilitySlow scribbles is then a
 * copy of its own, and the tree this points at stays pristine.
 *
 * Being non-NULL is also what tells the event trigger below that it is firing
 * for a statement this module intercepted, rather than for some unrelated
 * DDL, and that the raw statement therefore matches the commands it is about
 * to deparse.
 */
static const Node *capture_parsetree = NULL;

/*
 * JSON blob deparsed for that statement; allocated in TopTransactionContext
 * so it survives the rollback of the internal subtransaction the trial run
 * executes in.  Only valid while capture_parsetree is set.
 *
 * A single pointer, not a list: one intercepted statement is one complete
 * query, which fires the capture event trigger exactly once (sub-commands
 * such as the internal ALTER TABLE ADD CONSTRAINT generated by a CREATE
 * TABLE with a foreign key are collected into that one firing, not fired
 * separately), and one firing deparses to exactly one command.  The trigger
 * errors out if that invariant is ever broken.
 */
static char *captured_json = NULL;

/* Are we re-executing a deparsed command ourselves? */
static bool in_roundtrip = false;

static void test_ddl_deparse_utility_command(PlannedStmt *pstmt,
											 const char *queryString,
											 bool readOnlyTree,
											 ProcessUtilityContext context,
											 ParamListInfo params,
											 QueryEnvironment *queryEnv,
											 DestReceiver *dest,
											 QueryCompletion *qc);
static void test_ddl_deparse_error_callback(void *arg);
static void report_declined_command(Node *stmt, const char *queryString);

void
_PG_init(void)
{
	DefineCustomBoolVariable("test_ddl_deparse.execute_deparsed_ddl",
							 "Replace supported DDL commands with their deparsed version.",
							 NULL,
							 &execute_deparsed_ddl,
							 false,
							 PGC_USERSET,
							 0,
							 NULL, NULL, NULL);

	DefineCustomEnumVariable("test_ddl_deparse.print_deparsed_ddl",
							 "Report the deparsed DDL command as a NOTICE, in the given form.",
							 NULL,
							 &print_deparsed_ddl,
							 PRINT_DEPARSED_OFF,
							 print_deparsed_ddl_options,
							 PGC_USERSET,
							 0,
							 NULL, NULL, NULL);

	DefineCustomBoolVariable("test_ddl_deparse.log_declined_commands",
							 "Log DDL commands the deparser declined to reproduce.",
							 NULL,
							 &log_declined_commands,
							 false,
							 PGC_USERSET,
							 0,
							 NULL, NULL, NULL);

	MarkGUCPrefixReserved("test_ddl_deparse");

	next_ProcessUtility_hook = ProcessUtility_hook;
	ProcessUtility_hook = test_ddl_deparse_utility_command;
}

/*
 * ddl_command_end event trigger: deparse the commands collected for the
 * statement being captured, and remember the result for replay.
 *
 * This is where the deparser has to run: the collected commands live in the
 * event trigger state, which ProcessUtilitySlow discards as soon as the
 * complete query is done, so there is no later moment at which to ask for
 * them.  The event trigger machinery has already done a
 * CommandCounterIncrement, so the catalog entries the deparser reads are
 * visible.
 *
 * For a statement whose deparsed form is to be executed, this runs inside the
 * internal subtransaction started by test_ddl_deparse_utility_command, so the
 * JSON string is copied into TopTransactionContext, which survives that
 * subtransaction's rollback.
 *
 * With print_deparsed_ddl enabled, the deparsed command is reported as a
 * NOTICE whether or not it is going to be executed in place of the original.
 */
Datum
capture_deparsed_ddl(PG_FUNCTION_ARGS)
{
	char	   *json;

	if (!CALLED_AS_EVENT_TRIGGER(fcinfo))
		elog(ERROR, "not fired by event trigger manager");

	/*
	 * Do nothing unless a statement of ours is being captured.  This is the
	 * common case: the trigger is installed for the whole session, but only
	 * top-level statements the module intercepts have a raw parse tree saved
	 * for the deparser to work from.
	 */
	if (capture_parsetree == NULL)
		PG_RETURN_NULL();

	/*
	 * A second firing while one statement is being captured means a nested
	 * complete query (say, DDL run by another event trigger function) also
	 * produced a supported command.  Its raw statement is not the one saved
	 * above, and replaying both would double-execute the nested one when the
	 * replayed outer statement triggers it again, so refuse loudly.
	 */
	if (captured_json != NULL)
		elog(ERROR, "multiple DDL deparse captures for a single statement");

	json = deparse_ddl_command(capture_parsetree,
							   EventTriggerGetCollectedCommands());
	if (json == NULL)
		PG_RETURN_NULL();

	if (print_deparsed_ddl == PRINT_DEPARSED_JSON ||
		print_deparsed_ddl == PRINT_DEPARSED_BOTH)
		ereport(NOTICE,
				(errmsg("deparsed JSON: %s", json),
				 errhidestmt(true),
				 errhidecontext(true)));

	if (print_deparsed_ddl == PRINT_DEPARSED_TEXT ||
		print_deparsed_ddl == PRINT_DEPARSED_BOTH)
		ereport(NOTICE,
				(errmsg("deparsed DDL: %s", deparse_ddl_json_to_string(json)),
				 errhidestmt(true),
				 errhidecontext(true)));

	captured_json = MemoryContextStrdup(TopTransactionContext, json);

	PG_RETURN_NULL();
}

/*
 * Continue with the rest of the ProcessUtility hook chain (or standard
 * processing if we are the last hook).  Used for every execution this module
 * initiates, so that other loaded modules' hooks are not bypassed; re-entry
 * into our own interception is prevented by the in_roundtrip flag and by the
 * fact that this call sits below our hook in the chain.
 */
static void
call_next_ProcessUtility(PlannedStmt *pstmt,
						 const char *queryString,
						 bool readOnlyTree,
						 ProcessUtilityContext context,
						 ParamListInfo params,
						 QueryEnvironment *queryEnv,
						 DestReceiver *dest, QueryCompletion *qc)
{
	if (next_ProcessUtility_hook)
		next_ProcessUtility_hook(pstmt, queryString, readOnlyTree,
								 context, params, queryEnv, dest, qc);
	else
		standard_ProcessUtility(pstmt, queryString, readOnlyTree,
								context, params, queryEnv, dest, qc);
}

/*
 * Parse and execute one deparsed DDL command.
 *
 * The whole point of this module is to surface deparser bugs, so any shape
 * surprise in the deparsed string is reported as an error (with the string
 * in the error context), not assumed away: one DDL command must deparse to
 * exactly one DDL command.
 *
 */
static void
execute_deparsed_command(const char *sql,
						 ProcessUtilityContext context,
						 ParamListInfo params,
						 QueryEnvironment *queryEnv,
						 DestReceiver *dest, QueryCompletion *qc)
{
	List	   *parsetree_list;
	RawStmt    *rs;
	List	   *querytree_list;
	PlannedStmt *pstmt;
	Query	   *query;
	int			save_nestlevel;

	save_nestlevel = NewGUCNestLevel();

	/*
	 * Messages that the replayed command would emit have already been emitted
	 * by the original execution, so suppress them.
	 */
	(void) set_config_option("client_min_messages", "error",
							 PGC_USERSET, PGC_S_SESSION,
							 GUC_ACTION_SAVE, true, 0, false);

	/*
	 * Execute the deparsed command under a restricted search_path, the same
	 * environment the deparser itself produces its output under.  Deparsed
	 * DDL is supposed to be safe to execute regardless of the search_path in
	 * effect (everything schema-qualified except pg_catalog references);
	 * replaying it this way makes any missing qualification fail visibly
	 * instead of silently resolving through the session's own search_path.
	 * The surrounding GUC nest level undoes this below.
	 */
	RestrictSearchPath();

	parsetree_list = pg_parse_query(sql);
	if (list_length(parsetree_list) != 1)
		elog(ERROR, "deparsed DDL is not a single command: %s", sql);

	rs = linitial_node(RawStmt, parsetree_list);
	querytree_list = pg_analyze_and_rewrite_fixedparams(rs, sql, NULL, 0,
														NULL);
	if (list_length(querytree_list) != 1)
		elog(ERROR, "deparsed DDL did not analyze to a single query: %s", sql);

	query = linitial_node(Query, querytree_list);
	if (query->commandType != CMD_UTILITY)
		elog(ERROR, "deparsed DDL is not a utility command: %s", sql);

	pstmt = makeNode(PlannedStmt);
	pstmt->commandType = CMD_UTILITY;
	pstmt->canSetTag = true;
	pstmt->utilityStmt = query->utilityStmt;
	pstmt->stmt_location = rs->stmt_location;
	pstmt->stmt_len = rs->stmt_len;

	call_next_ProcessUtility(pstmt, sql, false,
							 context, params, queryEnv,
							 dest, qc);

	AtEOXact_GUC(true, save_nestlevel);
}

/*
 * ProcessUtility hook: capture supported DDL commands and, when
 * execute_deparsed_ddl is set, replace them with their deparsed
 * reconstruction.
 *
 * Capturing a statement means saving it for the event trigger above and
 * running it with readOnlyTree forced on, so that the saved tree stays as the
 * user wrote it while the copy execution works on is rewritten in place.
 *
 * For the replacement, the original statement is executed in an internal
 * subtransaction that is rolled back afterwards; its execution fires the
 * capture event trigger, which deparses the collected commands.  The
 * reconstructed command is then executed for real.  Divergence between the
 * two forms thus shows up in the regular regression output.
 */
static void
test_ddl_deparse_utility_command(PlannedStmt *pstmt,
								 const char *queryString,
								 bool readOnlyTree,
								 ProcessUtilityContext context,
								 ParamListInfo params,
								 QueryEnvironment *queryEnv,
								 DestReceiver *dest, QueryCompletion *qc)
{
	/*
	 * Only top-level statements are captured, and only when something is
	 * going to be done with the result.  Our own replay of a deparsed command
	 * must not be captured in turn.
	 */
	if (context != PROCESS_UTILITY_TOPLEVEL || in_roundtrip ||
		(!execute_deparsed_ddl && print_deparsed_ddl == PRINT_DEPARSED_OFF))
	{
		call_next_ProcessUtility(pstmt, queryString, readOnlyTree,
								 context, params, queryEnv, dest, qc);
		return;
	}

	/*
	 * A command the deparser declines executes unchanged.  That is the right
	 * thing for a test run -- one gap must not stop the rest of the suite --
	 * but it means the command is simply not tested, and nothing says so.
	 * Report it, so that a deparser gap is a thing one can go and look at
	 * rather than an absence nobody notices.
	 */
	if (!ddl_deparse_command_supported(pstmt->utilityStmt))
	{
		report_declined_command(pstmt->utilityStmt, queryString);
		call_next_ProcessUtility(pstmt, queryString, readOnlyTree,
								 context, params, queryEnv, dest, qc);
		return;
	}

	captured_json = NULL;
	capture_parsetree = pstmt->utilityStmt;

	PG_TRY();
	{
		if (!execute_deparsed_ddl)
		{
			/*
			 * Nothing to replace: run the command for real, captured only so
			 * that the event trigger reports its deparsed form.
			 */
			call_next_ProcessUtility(pstmt, queryString, true,
									 context, params, queryEnv, dest, qc);
		}
		else
		{
			MemoryContext oldcontext = CurrentMemoryContext;
			ResourceOwner oldowner = CurrentResourceOwner;

			/*
			 * Run the trial in an internal subtransaction, following the
			 * standard idiom (cf. plpgsql): save and restore the caller's
			 * memory context and resource owner around it, so the replay
			 * below runs in the same environment the statement arrived in.
			 */
			BeginInternalSubTransaction("test_ddl_deparse");
			MemoryContextSwitchTo(oldcontext);
			PG_TRY(2);
			{
				call_next_ProcessUtility(pstmt, queryString, true,
										 context, params, queryEnv, dest, qc);

				RollbackAndReleaseCurrentSubTransaction();
				MemoryContextSwitchTo(oldcontext);
				CurrentResourceOwner = oldowner;
			}
			PG_CATCH(2);
			{
				RollbackAndReleaseCurrentSubTransaction();
				MemoryContextSwitchTo(oldcontext);
				CurrentResourceOwner = oldowner;
				PG_RE_THROW();
			}
			PG_END_TRY(2);

			/*
			 * The capture window closes with the trial: whatever DDL runs
			 * from here on -- the replay itself, or the original command in
			 * the fallback below -- fires the event trigger again, and must
			 * not be taken for this statement.
			 */
			capture_parsetree = NULL;

			if (captured_json == NULL)
			{
				Node	   *stmt = pstmt->utilityStmt;
				bool		noop;

				/*
				 * The deparser produced nothing.  The benign case is an IF
				 * NOT EXISTS command that did nothing (the trial execution
				 * has already emitted the "skipping" notice), so there is
				 * nothing to replay; anything else is unexpected, so warn and
				 * run the original command for real rather than silently
				 * losing it.  The IsA check matters: once more command types
				 * are supported, if_not_exists must only be consulted on
				 * statements that actually have the field.
				 */
				noop = (IsA(stmt, CreateStmt) &&
						((CreateStmt *) stmt)->if_not_exists);
				if (!noop)
				{
					ereport(WARNING,
							(errmsg("could not deparse DDL command, executing the original"),
							 errdetail("Command: %s", queryString)));
					call_next_ProcessUtility(pstmt, queryString, readOnlyTree,
											 context, params, queryEnv, dest, qc);
				}
			}
			else
			{
				ErrorContextCallback errcallback;
				TestDDLDeparseErrorInfo errinfo;
				char	   *sql;

				sql = deparse_ddl_json_to_string(captured_json);

				errinfo.orig_ddl = queryString;
				errinfo.deparsed_ddl = sql;

				errcallback.callback = test_ddl_deparse_error_callback;
				errcallback.previous = error_context_stack;
				errcallback.arg = &errinfo;
				error_context_stack = &errcallback;

				in_roundtrip = true;
				PG_TRY(2);
				{
					execute_deparsed_command(sql, context, params, queryEnv,
											 dest, qc);
				}
				PG_FINALLY(2);
				{
					in_roundtrip = false;
				}
				PG_END_TRY(2);

				error_context_stack = errcallback.previous;
			}
		}
	}
	PG_FINALLY();
	{
		capture_parsetree = NULL;
		/* don't leave a dangling pointer into transaction-lifetime memory */
		captured_json = NULL;
	}
	PG_END_TRY();
}

/*
 * Report a top-level command that the deparser declined.
 *
 * Only statement types deparse_ddl_command() has a case for are reported: for
 * those, a decline is a gap in the deparser, whereas for anything else it
 * just means the statement is not this deparser's business.  Note that even
 * so a report is not by itself a defect -- ALTER FUNCTION ... RENAME is
 * declined because RENAME is only supported for tables and columns, and that
 * is by design.  What matters is that the set of reports is visible, so that
 * one that ought not to be there can be noticed.
 *
 * This goes to the server log rather than to the client so that enabling it
 * does not perturb the output of the regression tests being replayed.
 */
static void
report_declined_command(Node *stmt, const char *queryString)
{
	if (!log_declined_commands)
		return;

	switch (nodeTag(stmt))
	{
		case T_CreateStmt:
		case T_AlterTableStmt:
		case T_RenameStmt:
		case T_AlterObjectSchemaStmt:
			break;
		default:
			return;
	}

	ereport(LOG,
			(errmsg("test_ddl_deparse: declined %s: %s",
					CreateCommandName(stmt), queryString),
			 errhidestmt(true),
			 errhidecontext(true)));
}

static void
test_ddl_deparse_error_callback(void *arg)
{
	TestDDLDeparseErrorInfo *errinfo = (TestDDLDeparseErrorInfo *) arg;

	errcontext("original DDL \"%s\", deparsed DDL \"%s\"",
			   errinfo->orig_ddl,
			   errinfo->deparsed_ddl ? errinfo->deparsed_ddl : "(none)");
}

/*
 * Return the textual representation of the struct type used to represent a
 * command in struct CollectedCommand format.
 */
Datum
get_command_type(PG_FUNCTION_ARGS)
{
	CollectedCommand *cmd = (CollectedCommand *) PG_GETARG_POINTER(0);
	const char *type;

	switch (cmd->type)
	{
		case SCT_Simple:
			type = "simple";
			break;
		case SCT_AlterTable:
			type = "alter table";
			break;
		case SCT_Grant:
			type = "grant";
			break;
		case SCT_AlterOpFamily:
			type = "alter operator family";
			break;
		case SCT_AlterDefaultPrivileges:
			type = "alter default privileges";
			break;
		case SCT_CreateOpClass:
			type = "create operator class";
			break;
		case SCT_AlterTSConfig:
			type = "alter text search configuration";
			break;
		default:
			type = "unknown command type";
			break;
	}

	PG_RETURN_TEXT_P(cstring_to_text(type));
}

/*
 * Return the command tag corresponding to a parse node contained in a
 * CollectedCommand struct.
 */
Datum
get_command_tag(PG_FUNCTION_ARGS)
{
	CollectedCommand *cmd = (CollectedCommand *) PG_GETARG_POINTER(0);

	if (!cmd->parsetree)
		PG_RETURN_NULL();

	PG_RETURN_TEXT_P(cstring_to_text(CreateCommandName(cmd->parsetree)));
}

/*
 * Return a text array representation of the subcommands of an ALTER TABLE
 * command.
 */
Datum
get_altertable_subcmdinfo(PG_FUNCTION_ARGS)
{
	CollectedCommand *cmd = (CollectedCommand *) PG_GETARG_POINTER(0);
	ListCell   *cell;
	ReturnSetInfo *rsinfo = (ReturnSetInfo *) fcinfo->resultinfo;

	if (cmd->type != SCT_AlterTable)
		elog(ERROR, "command is not ALTER TABLE");

	InitMaterializedSRF(fcinfo, 0);

	if (cmd->d.alterTable.subcmds == NIL)
		elog(ERROR, "empty alter table subcommand list");

	foreach(cell, cmd->d.alterTable.subcmds)
	{
		CollectedATSubcmd *sub = lfirst(cell);
		AlterTableCmd *subcmd = castNode(AlterTableCmd, sub->parsetree);
		const char *strtype = "unrecognized";
		Datum		values[2];
		bool		nulls[2];

		memset(values, 0, sizeof(values));
		memset(nulls, 0, sizeof(nulls));

		switch (subcmd->subtype)
		{
			case AT_AddColumn:
				strtype = "ADD COLUMN";
				break;
			case AT_AddColumnToView:
				strtype = "ADD COLUMN TO VIEW";
				break;
			case AT_ColumnDefault:
				strtype = "ALTER COLUMN SET DEFAULT";
				break;
			case AT_CookedColumnDefault:
				strtype = "ALTER COLUMN SET DEFAULT (precooked)";
				break;
			case AT_DropNotNull:
				strtype = "DROP NOT NULL";
				break;
			case AT_SetNotNull:
				strtype = "SET NOT NULL";
				break;
			case AT_SetExpression:
				strtype = "SET EXPRESSION";
				break;
			case AT_DropExpression:
				strtype = "DROP EXPRESSION";
				break;
			case AT_SetStatistics:
				strtype = "SET STATS";
				break;
			case AT_SetOptions:
				strtype = "SET OPTIONS";
				break;
			case AT_ResetOptions:
				strtype = "RESET OPTIONS";
				break;
			case AT_SetStorage:
				strtype = "SET STORAGE";
				break;
			case AT_SetCompression:
				strtype = "SET COMPRESSION";
				break;
			case AT_DropColumn:
				strtype = "DROP COLUMN";
				break;
			case AT_AddIndex:
				strtype = "ADD INDEX";
				break;
			case AT_ReAddIndex:
				strtype = "(re) ADD INDEX";
				break;
			case AT_AddConstraint:
				strtype = "ADD CONSTRAINT";
				break;
			case AT_ReAddConstraint:
				strtype = "(re) ADD CONSTRAINT";
				break;
			case AT_ReAddDomainConstraint:
				strtype = "(re) ADD DOMAIN CONSTRAINT";
				break;
			case AT_AlterConstraint:
				strtype = "ALTER CONSTRAINT";
				break;
			case AT_ValidateConstraint:
				strtype = "VALIDATE CONSTRAINT";
				break;
			case AT_AddIndexConstraint:
				strtype = "ADD CONSTRAINT (using index)";
				break;
			case AT_DropConstraint:
				strtype = "DROP CONSTRAINT";
				break;
			case AT_ReAddComment:
				strtype = "(re) ADD COMMENT";
				break;
			case AT_AlterColumnType:
				strtype = "ALTER COLUMN SET TYPE";
				break;
			case AT_AlterColumnGenericOptions:
				strtype = "ALTER COLUMN SET OPTIONS";
				break;
			case AT_ChangeOwner:
				strtype = "CHANGE OWNER";
				break;
			case AT_ClusterOn:
				strtype = "CLUSTER";
				break;
			case AT_DropCluster:
				strtype = "DROP CLUSTER";
				break;
			case AT_SetLogged:
				strtype = "SET LOGGED";
				break;
			case AT_SetUnLogged:
				strtype = "SET UNLOGGED";
				break;
			case AT_DropOids:
				strtype = "DROP OIDS";
				break;
			case AT_SetAccessMethod:
				strtype = "SET ACCESS METHOD";
				break;
			case AT_SetTableSpace:
				strtype = "SET TABLESPACE";
				break;
			case AT_SetRelOptions:
				strtype = "SET RELOPTIONS";
				break;
			case AT_ResetRelOptions:
				strtype = "RESET RELOPTIONS";
				break;
			case AT_ReplaceRelOptions:
				strtype = "REPLACE RELOPTIONS";
				break;
			case AT_EnableTrig:
				strtype = "ENABLE TRIGGER";
				break;
			case AT_EnableAlwaysTrig:
				strtype = "ENABLE TRIGGER (always)";
				break;
			case AT_EnableReplicaTrig:
				strtype = "ENABLE TRIGGER (replica)";
				break;
			case AT_DisableTrig:
				strtype = "DISABLE TRIGGER";
				break;
			case AT_EnableTrigAll:
				strtype = "ENABLE TRIGGER (all)";
				break;
			case AT_DisableTrigAll:
				strtype = "DISABLE TRIGGER (all)";
				break;
			case AT_EnableTrigUser:
				strtype = "ENABLE TRIGGER (user)";
				break;
			case AT_DisableTrigUser:
				strtype = "DISABLE TRIGGER (user)";
				break;
			case AT_EnableRule:
				strtype = "ENABLE RULE";
				break;
			case AT_EnableAlwaysRule:
				strtype = "ENABLE RULE (always)";
				break;
			case AT_EnableReplicaRule:
				strtype = "ENABLE RULE (replica)";
				break;
			case AT_DisableRule:
				strtype = "DISABLE RULE";
				break;
			case AT_AddInherit:
				strtype = "ADD INHERIT";
				break;
			case AT_DropInherit:
				strtype = "DROP INHERIT";
				break;
			case AT_AddOf:
				strtype = "OF";
				break;
			case AT_DropOf:
				strtype = "NOT OF";
				break;
			case AT_ReplicaIdentity:
				strtype = "REPLICA IDENTITY";
				break;
			case AT_EnableRowSecurity:
				strtype = "ENABLE ROW SECURITY";
				break;
			case AT_DisableRowSecurity:
				strtype = "DISABLE ROW SECURITY";
				break;
			case AT_ForceRowSecurity:
				strtype = "FORCE ROW SECURITY";
				break;
			case AT_NoForceRowSecurity:
				strtype = "NO FORCE ROW SECURITY";
				break;
			case AT_GenericOptions:
				strtype = "SET OPTIONS";
				break;
			case AT_DetachPartition:
				strtype = "DETACH PARTITION";
				break;
			case AT_AttachPartition:
				strtype = "ATTACH PARTITION";
				break;
			case AT_DetachPartitionFinalize:
				strtype = "DETACH PARTITION ... FINALIZE";
				break;
			case AT_SplitPartition:
				strtype = "SPLIT PARTITION";
				break;
			case AT_MergePartitions:
				strtype = "MERGE PARTITIONS";
				break;
			case AT_AddIdentity:
				strtype = "ADD IDENTITY";
				break;
			case AT_SetIdentity:
				strtype = "SET IDENTITY";
				break;
			case AT_DropIdentity:
				strtype = "DROP IDENTITY";
				break;
			case AT_ReAddStatistics:
				strtype = "(re) ADD STATS";
				break;
		}

		if (subcmd->recurse)
			values[0] = CStringGetTextDatum(psprintf("%s (and recurse)", strtype));
		else
			values[0] = CStringGetTextDatum(strtype);
		if (OidIsValid(sub->address.objectId))
		{
			char	   *objdesc;

			objdesc = getObjectDescription((const ObjectAddress *) &sub->address, false);
			values[1] = CStringGetTextDatum(objdesc);
		}
		else
			nulls[1] = true;

		tuplestore_putvalues(rsinfo->setResult, rsinfo->setDesc, values, nulls);
	}

	return (Datum) 0;
}
