#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/keyring
#
# IDENTIFICATION
#    src/backend/storage/keyring/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/keyring
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = keyring.o

include $(top_srcdir)/src/backend/common.mk
