--
-- Tests for DDL deparsing of CREATE TABLE.
--
-- Note: the event triggers created by the test_ddl_deparse script (which
-- must run first in this schedule) remain installed, so their "DDL test:"
-- NOTICEs appear interleaved below; deparse capture itself does not use
-- them.
--
-- With test_ddl_deparse.execute_deparsed_ddl enabled, the module
-- intercepts each supported CREATE TABLE: the original command is executed
-- in a subtransaction that is rolled back, the collected command is
-- deparsed to JSON, and the reconstructed command is executed for real.
-- With print_deparsed_ddl enabled the reconstructed command is shown as a
-- NOTICE, so the expected output asserts the deparsed text itself; exactly
-- one NOTICE per statement shows that one DDL deparses to one DDL.
--
LOAD 'test_ddl_deparse';
SET test_ddl_deparse.execute_deparsed_ddl = on;
SET test_ddl_deparse.print_deparsed_ddl = text;

CREATE SCHEMA deparse_tests;

-- simple case
CREATE TABLE deparse_tests.t1 (a int, b text);

-- serial must stay serial: no sequence creation and no nextval() default
-- may appear in the deparsed command, but the replayed table must still
-- have them.
CREATE TABLE deparse_tests.t_serial (id serial, big bigserial NOT NULL);
SELECT attname, pg_get_serial_sequence('deparse_tests.t_serial', attname) AS seq
  FROM pg_attribute
  WHERE attrelid = 'deparse_tests.t_serial'::regclass AND attnum > 0
  ORDER BY attnum;

-- COMPRESSION and STORAGE appear only when the user wrote them; columns
-- without the clause must adopt the target's defaults on replay
-- (attcompression stays unset).
CREATE TABLE deparse_tests.t_options (
a text COMPRESSION pglz,
b text STORAGE external,
c text
);
SELECT attname, attcompression, attstorage
  FROM pg_attribute
  WHERE attrelid = 'deparse_tests.t_options'::regclass AND attnum > 0
  ORDER BY attnum;

-- inline constraints are normalized to table constraints, but stay within
-- the single CREATE TABLE command; unnamed constraints get the same
-- auto-derived name on replay.
CREATE TABLE deparse_tests.t_constr (
a int PRIMARY KEY,
b int REFERENCES deparse_tests.t_constr (a) NOT NULL,
c text DEFAULT 'x' CHECK (c <> ''),
CONSTRAINT named_check CHECK (a > 0)
);
SELECT conname, contype, pg_get_constraintdef(oid)
  FROM pg_constraint
  WHERE conrelid = 'deparse_tests.t_constr'::regclass
  ORDER BY conname COLLATE "C";

-- table-level NOT NULL constraint syntax
CREATE TABLE deparse_tests.t_tblnotnull (a int, CONSTRAINT nn_a NOT NULL a);

-- type names are normalized but keep their typmod; interval exercises
-- SQL-standard types with special typmod rules
CREATE TABLE deparse_tests.t_types (
a varchar(10),
b numeric(10,2),
c timestamp(3),
d interval hour to minute,
e int[]
);

-- identity columns: sequence options are emitted only as far as the user
-- gave them
CREATE TABLE deparse_tests.t_identity (
a int GENERATED ALWAYS AS IDENTITY,
b int GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5)
);
SELECT seqstart, seqincrement
  FROM pg_sequence
  WHERE seqrelid = pg_get_serial_sequence('deparse_tests.t_identity', 'b')::regclass;

-- generated columns
CREATE TABLE deparse_tests.t_generated (
a int,
b int GENERATED ALWAYS AS (a * 2) STORED,
c int GENERATED ALWAYS AS (a + 1) VIRTUAL
);

-- defaults referencing other objects come out schema-qualified
CREATE SEQUENCE deparse_tests.myseq;
CREATE TABLE deparse_tests.t_defaults (
a timestamptz DEFAULT now(),
b int DEFAULT nextval('deparse_tests.myseq')
);

-- collation
CREATE TABLE deparse_tests.t_collate (a text COLLATE "C");

-- persistence
CREATE UNLOGGED TABLE deparse_tests.t_unlogged (a int);

-- reloptions, only as typed
CREATE TABLE deparse_tests.t_withopts (a int)
	WITH (fillfactor = 70, autovacuum_enabled = false);

-- inheritance
CREATE TABLE deparse_tests.t_parent (a int NOT NULL, b text);
CREATE TABLE deparse_tests.t_child () INHERITS (deparse_tests.t_parent);

-- partitioning
CREATE TABLE deparse_tests.t_part (a int, b text) PARTITION BY RANGE (a);
CREATE TABLE deparse_tests.t_part1 PARTITION OF deparse_tests.t_part
	FOR VALUES FROM (1) TO (10);
CREATE TABLE deparse_tests.t_part2 PARTITION OF deparse_tests.t_part
	(b WITH OPTIONS NOT NULL)
	FOR VALUES FROM (10) TO (20);
CREATE TABLE deparse_tests.t_partd PARTITION OF deparse_tests.t_part DEFAULT;

-- typed table
CREATE TYPE deparse_tests.comp AS (x int, y text);
CREATE TABLE deparse_tests.t_of OF deparse_tests.comp (x WITH OPTIONS NOT NULL);

-- exclusion constraint
CREATE TABLE deparse_tests.t_excl (
c circle,
EXCLUDE USING gist (c WITH &&)
);

-- quoted identifiers
CREATE TABLE deparse_tests."Mixed Case" ("Col A" int, "select" text);

-- IF NOT EXISTS on an existing relation deparses to nothing and must not
-- be replayed
CREATE TABLE IF NOT EXISTS deparse_tests.t1 (a int);

-- LIKE contributes columns that are not in the raw statement, so they are
-- recovered from the catalog.  Bare LIKE copies the type, its collation and
-- NOT NULL, and nothing else.
CREATE TABLE deparse_tests.t_like_src (
a int NOT NULL,
b text COLLATE "C",
c numeric(10,2) STORAGE plain,
d int DEFAULT 7,
e int GENERATED ALWAYS AS (d * 2) STORED
);
CREATE TABLE deparse_tests.t_like (LIKE deparse_tests.t_like_src);

-- columns the user did write are still deparsed from what they wrote, and
-- the catalog order keeps the two kinds interleaved as the command produced
-- them (serial stays serial, the copied columns come from pg_attribute)
CREATE TABLE deparse_tests.t_like_mixed (
x serial,
LIKE deparse_tests.t_like_src,
y int DEFAULT 1
);

-- the options that land in the table definition are all recovered
CREATE TABLE deparse_tests.t_like_incl (
LIKE deparse_tests.t_like_src
	INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING CONSTRAINTS
	INCLUDING STORAGE INCLUDING COMPRESSION
);

-- identity comes back with the sequence parameters that were copied
CREATE TABLE deparse_tests.t_like_idsrc (
a int GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5)
);
CREATE TABLE deparse_tests.t_like_ident
  (LIKE deparse_tests.t_like_idsrc INCLUDING IDENTITY);
SELECT seqstart, seqincrement
  FROM pg_sequence
  WHERE seqrelid = pg_get_serial_sequence('deparse_tests.t_like_ident', 'a')::regclass;

-- options that copy an object needing a statement of its own are declined:
-- the statement is not intercepted and executes normally
CREATE INDEX ON deparse_tests.t_like_src (a);
COMMENT ON COLUMN deparse_tests.t_like_src.a IS 'a comment';
CREATE TABLE deparse_tests.t_like_idx
  (LIKE deparse_tests.t_like_src INCLUDING INDEXES);
CREATE TABLE deparse_tests.t_like_cmt
  (LIKE deparse_tests.t_like_src INCLUDING COMMENTS);
CREATE TABLE deparse_tests.t_like_all
  (LIKE deparse_tests.t_like_src INCLUDING ALL);
SELECT relname FROM pg_class WHERE oid = 'deparse_tests.t_like'::regclass;

-- DEFAULT NULL stores no pg_attrdef entry but must still deparse
CREATE TABLE deparse_tests.t_defnull (a int DEFAULT NULL, b text DEFAULT NULL::text);

-- identity sequence options that parse analysis consumes are still in the
-- raw parse tree: SEQUENCE NAME must deparse; OWNED BY is dropped, since
-- execution overrides it (the sequence is always owned by the identity
-- column) and the name it carries need not be replayable
CREATE TABLE deparse_tests.t_seqname (
id int GENERATED ALWAYS AS IDENTITY
	(SEQUENCE NAME deparse_tests.t_seqname_seq START WITH 5)
);
SELECT relname FROM pg_class WHERE oid = 'deparse_tests.t_seqname_seq'::regclass;
CREATE TABLE deparse_tests.t_ownedby (
id int GENERATED BY DEFAULT AS IDENTITY
	(OWNED BY NONE)
);
CREATE TABLE deparse_tests.t_owner (x int);
CREATE TABLE deparse_tests.t_ownedby2 (
id int GENERATED ALWAYS AS IDENTITY
	(OWNED BY deparse_tests.t_owner.x START WITH 7)
);
SELECT pg_get_serial_sequence('deparse_tests.t_ownedby2', 'id');

-- USING INDEX TABLESPACE must stay attached to the constraint that carried
-- it, also when several unnamed constraints of the same type exist
CREATE TABLE deparse_tests.t_idxtblspc (
a int,
b int,
c int,
UNIQUE (a),
UNIQUE (b) USING INDEX TABLESPACE pg_default,
PRIMARY KEY (c)
);

-- UNIQUE constraint variants, all via pg_get_constraintdef
CREATE TABLE deparse_tests.t_unique (
a int UNIQUE,
b int,
c int,
d int,
UNIQUE NULLS NOT DISTINCT (b),
UNIQUE (c) INCLUDE (d),
CONSTRAINT defer_u UNIQUE (d) DEFERRABLE INITIALLY DEFERRED
);
SELECT conname, pg_get_constraintdef(oid)
  FROM pg_constraint
  WHERE conrelid = 'deparse_tests.t_unique'::regclass
  ORDER BY conname COLLATE "C";

-- foreign key matching and referential actions
CREATE TABLE deparse_tests.t_fkref (a int, b int, PRIMARY KEY (a, b));
CREATE TABLE deparse_tests.t_fk (
x int,
y int,
FOREIGN KEY (x, y) REFERENCES deparse_tests.t_fkref (a, b)
	MATCH FULL ON DELETE CASCADE ON UPDATE SET NULL
);

-- temp tables and ON COMMIT; the temp schema is emitted as pg_temp
CREATE TEMP TABLE t_temp (a int);
CREATE TEMP TABLE t_temp_delrows (a int) ON COMMIT DELETE ROWS;
BEGIN;
CREATE TEMP TABLE t_temp_drop (a int) ON COMMIT DROP;
COMMIT;
DROP TABLE t_temp, t_temp_delrows;

-- access method and tablespace, only as typed
CREATE TABLE deparse_tests.t_tblspc (a int) USING heap TABLESPACE pg_default;

-- partitioning: list and hash, key expressions, opclass and collation
CREATE TABLE deparse_tests.t_list (a text COLLATE "C", b int)
	PARTITION BY LIST (a COLLATE "POSIX" text_pattern_ops);
CREATE TABLE deparse_tests.t_list1 PARTITION OF deparse_tests.t_list
	FOR VALUES IN ('x', 'y');
CREATE TABLE deparse_tests.t_list2 PARTITION OF deparse_tests.t_list
	(b WITH OPTIONS DEFAULT 42)
	FOR VALUES IN ('z');
CREATE TABLE deparse_tests.t_hash (a int, b text)
	PARTITION BY HASH ((a + length(b)));
CREATE TABLE deparse_tests.t_hash1 PARTITION OF deparse_tests.t_hash
	FOR VALUES WITH (MODULUS 4, REMAINDER 0);

-- identity sequence option spread
CREATE TABLE deparse_tests.t_identity2 (
a int GENERATED ALWAYS AS IDENTITY
	(MINVALUE 0 MAXVALUE 100 CACHE 10 CYCLE)
);

-- NO INHERIT forms
CREATE TABLE deparse_tests.t_noinh (
a int NOT NULL NO INHERIT,
b int CONSTRAINT chk_b CHECK (b > 0) NO INHERIT,
c int,
CONSTRAINT nn_c NOT NULL c NO INHERIT
);

-- multiple inheritance parents, in order
CREATE TABLE deparse_tests.t_parent2 (c int);
CREATE TABLE deparse_tests.t_multi ()
	INHERITS (deparse_tests.t_parent, deparse_tests.t_parent2);

-- more type and storage spellings: smallserial, array of typmod type,
-- STORAGE MAIN, and the COMPRESSION DEFAULT keyword
CREATE TABLE deparse_tests.t_types2 (
a smallserial,
b varchar(3)[],
c text STORAGE main,
d text COMPRESSION default
);

-- hostile names: format-string metacharacters and embedded quotes must
-- pass through the fmt expansion inertly
CREATE TABLE deparse_tests."evil %{name}I table" (
"a""b" int,
"%{col}s" text DEFAULT 'O''Reilly',
"100%" numeric
);
SELECT relname FROM pg_class WHERE relname = 'evil %{name}I table';

-- parse analysis merges redundant index constraints (the duplicate
-- UNIQUE (a), and UNIQUE (a) into the primary key); USING INDEX
-- TABLESPACE attribution must follow the surviving index of each
-- constraint, not raw-parse-tree positions
CREATE TABLE deparse_tests.t_dedup (
a int UNIQUE,
b int,
UNIQUE (a),
UNIQUE (b) USING INDEX TABLESPACE pg_default
);
CREATE TABLE deparse_tests.t_dedup2 (
a int,
b int,
UNIQUE (a),
UNIQUE (a),
UNIQUE (b) USING INDEX TABLESPACE pg_default,
PRIMARY KEY (a)
);

-- constraint attributes and the exclusion predicate come after USING
-- INDEX TABLESPACE in the grammar; the deparsed text must order them
-- accordingly
CREATE TABLE deparse_tests.t_deferidx (
a int,
b int,
UNIQUE (a) USING INDEX TABLESPACE pg_default DEFERRABLE INITIALLY DEFERRED,
PRIMARY KEY (b) USING INDEX TABLESPACE pg_default DEFERRABLE
);
CREATE TABLE deparse_tests.t_exclwhere (
c circle,
active bool,
EXCLUDE USING gist (c WITH &&)
	USING INDEX TABLESPACE pg_default WHERE (active) DEFERRABLE
);

-- index storage parameters on index-backed constraints, only as typed
CREATE TABLE deparse_tests.t_idxopts (
a int,
b int,
UNIQUE (a) WITH (fillfactor = 90),
PRIMARY KEY (b) WITH (fillfactor = 80, deduplicate_items = off)
	USING INDEX TABLESPACE pg_default DEFERRABLE
);
SELECT c.relname, c.reloptions
  FROM pg_class c
  WHERE c.relname IN ('t_idxopts_a_key', 't_idxopts_pkey')
  ORDER BY 1;

-- storage parameters of an exclusion constraint are already part of the
-- pg_get_constraintdef output and must not be emitted twice
CREATE TABLE deparse_tests.t_exclopts (
c circle,
EXCLUDE USING gist (c WITH &&) WITH (fillfactor = 70)
	USING INDEX TABLESPACE pg_default DEFERRABLE
);
SELECT c.relname, c.reloptions
  FROM pg_class c
  JOIN pg_constraint con ON con.conindid = c.oid
  WHERE con.conrelid = 'deparse_tests.t_exclopts'::regclass;

-- an exclusion predicate that the (indent-flavored) ruleutils output
-- renders across multiple lines must still split and replay correctly
CREATE TABLE deparse_tests.t_exclcase (
c circle,
n int,
EXCLUDE USING gist (c WITH &&)
	USING INDEX TABLESPACE pg_default
	WHERE (CASE WHEN n > 0 THEN true ELSE false END)
	DEFERRABLE
);
SELECT pg_get_constraintdef(oid)
  FROM pg_constraint
  WHERE conrelid = 'deparse_tests.t_exclcase'::regclass;

-- all optional exclusion-constraint clauses at once: the predicate strip
-- must operate on a body whose remaining suffix is the embedded WITH
CREATE TABLE deparse_tests.t_exclall (
c circle,
n int,
x int,
EXCLUDE USING gist (c WITH &&) INCLUDE (x)
	WITH (fillfactor = 60)
	USING INDEX TABLESPACE pg_default
	WHERE (CASE WHEN n > 0 THEN true ELSE false END)
	DEFERRABLE INITIALLY DEFERRED
);
SELECT pg_get_constraintdef(oid)
  FROM pg_constraint
  WHERE conrelid = 'deparse_tests.t_exclall'::regclass;

-- printing works whether or not the deparsed version is executed
SET test_ddl_deparse.execute_deparsed_ddl = off;
CREATE TABLE deparse_tests.t_printonly (a int);

-- the JSON blob itself can be printed, alone or along with the command
SET test_ddl_deparse.print_deparsed_ddl = json;
CREATE TABLE deparse_tests.t_json (id serial);
SET test_ddl_deparse.print_deparsed_ddl = 'both';
SET test_ddl_deparse.execute_deparsed_ddl = on;
CREATE TABLE deparse_tests.t_both (a int DEFAULT 42);

RESET test_ddl_deparse.print_deparsed_ddl;
RESET test_ddl_deparse.execute_deparsed_ddl;

DROP SCHEMA deparse_tests CASCADE;
