#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/kmgr
#
# IDENTIFICATION
#    src/backend/utils/kmgr/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/kmgr
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = kmgr.o kmgrfunc.o

include $(top_srcdir)/src/backend/common.mk
