#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for Key Managment System
#
# IDENTIFICATION
#    src/backend/kms/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/crypto
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = keyapi.o passphrase.o kmgr.o

include $(top_srcdir)/src/backend/common.mk
