#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/kmgr
#
# IDENTIFICATION
#    src/backend/storage/kmgr/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/kmgr
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = keyring.o masterkey.o tempkey.o plugin.o

include $(top_srcdir)/src/backend/common.mk
